### PR TITLE
token marketplace contract added

### PR DESCRIPTION
**Pull request by panditdhamdhere**
when building dex or token marketplace this contract can help beginners to get start with:

### CODE REVIEW

**Comment by anshss** [comment]
Hey @panditdhamdhere , if you can rename your folder to "dex" and your contract to something like token-swap would be more relevant to a naming convention, also try to have more specific comments for more clarity or help to save time in terms of understanding for major functions whereas not actually comments are needed for basic declarations like struct

**Comment by panditdhamdhere** [comment]
Hi @anshss just changed it please check this and **Thank you** for great suggestions.

**Comment by anshss** [comment]
Please update the name change in [Contributions.md ](https://github.com/easydweb/solidity-contracts/pull/1/files#diff-e487397d94fe9ebd659568e5ecccbb9ebdd6b407c5452a2360bbc2d58ebb630aR5)as well

**Comment by anshss** [comment]
@panditdhamdhere

**Comment by panditdhamdhere** [comment]
@anshss ohh no ! Done

**Pull request merged**
